export const APP_ROUTES = {
  AUTH: {
    LOGIN: 'login',
    REGISTER: 'register',
  },
  DASHBOARD: '',
  PROFILE: 'profile',
  USERS: {
    ROOT: 'users',
    DETAIL: 'users/:id',
  },
  ROLES: {
    ROOT: 'roles',
    DETAIL: 'roles/:id',
  },
  PERMISSIONS: {
    ROOT: 'permissions',
  },
  INVENTORY: {
    PRODUCTS: 'inventory/products',
    PRODUCT_DETAIL: 'inventory/products/:id',
    WAREHOUSES: 'inventory/warehouses',
    WAREHOUSE_DETAIL: 'inventory/warehouses/:id',
    WAREHOUSE_STOCKS: 'inventory/warehouse-stocks',
    TRANSACTIONS: 'inventory/transactions',
    STOCK_OPERATIONS: 'inventory/stock-operations',
  },
  SALES: {
    CUSTOMERS: 'sales/customers',
    CUSTOMER_DETAIL: 'sales/customers/:id',
    ORDERS: 'sales/orders',
    ORDER_DETAIL: 'sales/orders/:id',
  },
  PURCHASING: {
    SUPPLIERS: 'purchasing/suppliers',
    SUPPLIER_DETAIL: 'purchasing/suppliers/:id',
    ORDERS: 'purchasing/orders',
    ORDER_DETAIL: 'purchasing/orders/:id',
  },
  CRM: {
    LEADS: 'crm/leads',
    LEAD_NEW: 'crm/leads/new',
    LEAD_DETAIL: 'crm/leads/:id',
    OPPORTUNITIES: 'crm/opportunities',
    OPPORTUNITY_NEW: 'crm/opportunities/new',
    OPPORTUNITY_DETAIL: 'crm/opportunities/:id',
    ACTIVITIES: 'crm/activities',
    ACTIVITY_NEW: 'crm/activities/new',
    ACTIVITY_DETAIL: 'crm/activities/:id',
    ACCOUNTS: 'crm/accounts',
    ACCOUNT_DETAIL: 'crm/accounts/:id',
    CONTACTS: 'crm/contacts',
    CONTACT_NEW: 'crm/contacts/new',
    CONTACT_DETAIL: 'crm/contacts/:id',
  },
  BILLING: {
    INVOICES: 'billing/invoices',
    INVOICE_DETAIL: 'billing/invoices/:id',
    CREDIT_NOTES: 'billing/credit-notes',
    CREDIT_NOTE_DETAIL: 'billing/credit-notes/:id',
    PAYMENTS: 'billing/payments',
    PAYMENT_DETAIL: 'billing/payments/:id',
  },
} as const;

export const APP_PATHS = {
  AUTH: {
    LOGIN: `/${APP_ROUTES.AUTH.LOGIN}`,
    REGISTER: `/${APP_ROUTES.AUTH.REGISTER}`,
  },
  DASHBOARD: '/',
  PROFILE: `/${APP_ROUTES.PROFILE}`,
  USERS: {
    ROOT: `/${APP_ROUTES.USERS.ROOT}`,
    DETAIL: (id: string) => `/${APP_ROUTES.USERS.ROOT}/${id}`,
  },
  ROLES: {
    ROOT: `/${APP_ROUTES.ROLES.ROOT}`,
    DETAIL: (id: string) => `/${APP_ROUTES.ROLES.ROOT}/${id}`,
  },
  PERMISSIONS: {
    ROOT: `/${APP_ROUTES.PERMISSIONS.ROOT}`,
  },
  INVENTORY: {
    PRODUCTS: `/${APP_ROUTES.INVENTORY.PRODUCTS}`,
    PRODUCT_DETAIL: (id: string) => `/${APP_ROUTES.INVENTORY.PRODUCTS}/${id}`,
    WAREHOUSES: `/${APP_ROUTES.INVENTORY.WAREHOUSES}`,
    WAREHOUSE_DETAIL: (id: string) => `/${APP_ROUTES.INVENTORY.WAREHOUSES}/${id}`,
    WAREHOUSE_STOCKS: `/${APP_ROUTES.INVENTORY.WAREHOUSE_STOCKS}`,
    TRANSACTIONS: `/${APP_ROUTES.INVENTORY.TRANSACTIONS}`,
    STOCK_OPERATIONS: `/${APP_ROUTES.INVENTORY.STOCK_OPERATIONS}`,
  },
  SALES: {
    CUSTOMERS: `/${APP_ROUTES.SALES.CUSTOMERS}`,
    CUSTOMER_DETAIL: (id: string) => `/${APP_ROUTES.SALES.CUSTOMERS}/${id}`,
    ORDERS: `/${APP_ROUTES.SALES.ORDERS}`,
    ORDER_DETAIL: (id: string) => `/${APP_ROUTES.SALES.ORDERS}/${id}`,
  },
  PURCHASING: {
    SUPPLIERS: `/${APP_ROUTES.PURCHASING.SUPPLIERS}`,
    SUPPLIER_DETAIL: (id: string) => `/${APP_ROUTES.PURCHASING.SUPPLIERS}/${id}`,
    ORDERS: `/${APP_ROUTES.PURCHASING.ORDERS}`,
    ORDER_DETAIL: (id: string) => `/${APP_ROUTES.PURCHASING.ORDERS}/${id}`,
  },
  CRM: {
    LEADS: `/${APP_ROUTES.CRM.LEADS}`,
    LEAD_NEW: `/${APP_ROUTES.CRM.LEAD_NEW}`,
    LEAD_DETAIL: (id: string) => `/${APP_ROUTES.CRM.LEADS}/${id}`,
    OPPORTUNITIES: `/${APP_ROUTES.CRM.OPPORTUNITIES}`,
    OPPORTUNITY_NEW: `/${APP_ROUTES.CRM.OPPORTUNITY_NEW}`,
    OPPORTUNITY_DETAIL: (id: string) => `/${APP_ROUTES.CRM.OPPORTUNITIES}/${id}`,
    ACTIVITIES: `/${APP_ROUTES.CRM.ACTIVITIES}`,
    ACTIVITY_NEW: `/${APP_ROUTES.CRM.ACTIVITY_NEW}`,
    ACTIVITY_DETAIL: (id: string) => `/${APP_ROUTES.CRM.ACTIVITIES}/${id}`,
    ACCOUNTS: `/${APP_ROUTES.CRM.ACCOUNTS}`,
    ACCOUNT_DETAIL: (id: string) => `/${APP_ROUTES.CRM.ACCOUNTS}/${id}`,
    CONTACTS: `/${APP_ROUTES.CRM.CONTACTS}`,
    CONTACT_NEW: `/${APP_ROUTES.CRM.CONTACT_NEW}`,
    CONTACT_DETAIL: (id: string) => `/${APP_ROUTES.CRM.CONTACTS}/${id}`,
  },
  BILLING: {
    INVOICES: `/${APP_ROUTES.BILLING.INVOICES}`,
    INVOICE_DETAIL: (id: string) => `/${APP_ROUTES.BILLING.INVOICES}/${id}`,
    CREDIT_NOTES: `/${APP_ROUTES.BILLING.CREDIT_NOTES}`,
    CREDIT_NOTE_DETAIL: (id: string) => `/${APP_ROUTES.BILLING.CREDIT_NOTES}/${id}`,
    PAYMENTS: `/${APP_ROUTES.BILLING.PAYMENTS}`,
    PAYMENT_DETAIL: (id: string) => `/${APP_ROUTES.BILLING.PAYMENTS}/${id}`,
  },
} as const;
